events {}

http {
    upstream backend {
        server loadbalanced-api-api-1:5001;
        server loadbalanced-api-api-2:5001;
        server loadbalanced-api-api-3:5001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}
